services:
  server:
    build: './server'
    container_name: 'server'
    stdin_open: true
    tty: true
    environment:
      - ${URI}
      - ${TOKEN_SECRET}
      - ${PORT}
    depends_on:
      - mongodb

    client:
      build: './client'
      container_name: 'client'
      stdin_open: true
      tty: true

    nginx:
      image: nginx:latest
      container_name: 'nginx'
      ports:
        - '80:80'
        - '443:443'
      stdin_open: true
      tty: true
      depends_on:
        - server
        - client
      volumes:
        - ./nginx/ssl:/etc/letsencrypt/live/www.hash-view.com
        - ./nginx/nginx.conf:/etc/nginx/nginx.conf
